language: python

sudo: false

env:
  - TEST_SHELL_CMD=zsh
  - TEST_SHELL_CMD=bash

python:
  # - "2.6"
  # - "2.7"
  # - "3.2"
  # - "3.3"
  # - "3.4"
  # - "3.5"
  # - "3.5-dev" # 3.5 development branch
  - "3.6"
  # - "3.6-dev" # 3.6 development branch
  # - "3.7-dev" # 3.7 development branch
  # - "nightly" # currently points to 3.7-dev

cache:
  - pip: true
  - directories:
      - $HOME/mpi
      - $HOME/zsh

addons:
  apt:
    sources:
      - debian-sid
      - ubuntu-toolchain-r-test
    packages:
      - ibverbs-utils
      - libibverbs-dev

before_script:
  - sh ./.travis_install.sh

install:
  - pip install -r requirements.txt

script:
  - export PATH=$HOME/zsh/bin:$PATH
  - which zsh
  - autopep8 --diff -r . --global-config .pep8 | tee check_autopep8
  - test ! -s check_autopep8
  - flake8 $(find . -name "*.py")
  - coverage run $(which nosetests) -v
  - codeclimate-test-reporter # CODECLIMATE_REPO_TOKEN is defined in TravisCI's setting
